### ISSUE TITLE
_find_bucket(self, x: T)について

### ISSUE THREAD

**Issue by masa-aa** [tatyam-prime/SortedSet#1]
単調性があるから二分探索できると思います（早くなるかは微妙)

**Comment by tatyam-prime** [comment]
bucket_size が 50 ~ 150 くらいにしかならないので変数色々持つ二分探索よりシンプルな線形探索の方が速いんですよね

最初は二分探索していていました
https://github.com/tatyam-prime/SortedSet/commit/d2259de0298f7b0be4855c81042f3f3b21656413

**Comment by masa-aa** [comment]
ｱｯそうなんですね！ありがとうございます😭
